/**
 * 生成 seed 兜底快照 —— 把 data/prices-*.json 采集明细转成可打包的 TS 模块
 * ------------------------------------------------------------
 * 用法: npx tsx scripts/generate-seed-data.ts
 *
 * 读取 data/ 下最新一份 prices-YYYYMMDD.json，输出 lib/crawler/seed-prices.ts。
 * 输出采用「字符串常量 + JSON.parse」而非 JSON 导入，避免大 JSON 的 TS 类型推导开销。
 * 生成后重新构建部署，无 DB 环境（Vercel 预览/演示）即展示全量采集数据。
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

interface ExportPrice {
  tld: string
  currency?: string
  registerPrice: number | null
  renewPrice: number | null
  transferPrice: number | null
}
interface ExportRegistrar {
  name?: string
  website?: string
  currency?: string
  strategy?: string
  prices: ExportPrice[]
}
type ExportFile = { collectedAt: string; registrars: Record<string, ExportRegistrar> }

const dataDir = join(process.cwd(), "data")
const files = readdirSync(dataDir)
  .filter((f) => /^prices-\d{8}\.json$/.test(f))
  .sort()
if (files.length === 0) {
  console.error("data/ 下没有 prices-YYYYMMDD.json，先运行 scripts/export-prices.ts")
  process.exit(1)
}
const source = files[files.length - 1]
const raw = JSON.parse(readFileSync(join(dataDir, source), "utf8")) as ExportFile

// 快照：注册商与后缀字典序排列，保证生成文件可 diff；仅保留至少一条非空价格的记录
const registrars: Record<
  string,
  { name: string; website: string; currency: string; strategy: string | null; prices: Record<string, [number | null, number | null, number | null]> }
> = {}
let priceCount = 0
for (const slug of Object.keys(raw.registrars).sort()) {
  const r = raw.registrars[slug]
  const prices: Record<string, [number | null, number | null, number | null]> = {}
  for (const p of [...r.prices].sort((a, b) => a.tld.localeCompare(b.tld))) {
    if (p.registerPrice === null && p.renewPrice === null && p.transferPrice === null) continue
    prices[p.tld] = [p.registerPrice, p.renewPrice, p.transferPrice]
    priceCount++
  }
  if (Object.keys(prices).length === 0) continue
  registrars[slug] = {
    name: r.name ?? slug,
    website: r.website ?? `https://${slug}.com`,
    currency: r.currency ?? "USD",
    strategy: r.strategy ?? null,
    prices,
  }
}

const snapshot = { collectedAt: raw.collectedAt, registrars }
const json = JSON.stringify(snapshot)
const out = `// AUTO-GENERATED by scripts/generate-seed-data.ts —— 请勿手改
// 数据来源: data/${source} (collectedAt ${raw.collectedAt})
// 刷新方式: npx tsx scripts/generate-seed-data.ts

export const SEED_SNAPSHOT = JSON.parse(${JSON.stringify(json)}) as {
  collectedAt: string
  registrars: Record<
    string,
    {
      name: string
      website: string
      currency: string
      strategy: string | null
      prices: Record<string, [number | null, number | null, number | null]>
    }
  >
}
`
writeFileSync(join(process.cwd(), "lib", "crawler", "seed-prices.ts"), out)
console.log(
  `已生成 lib/crawler/seed-prices.ts: ${Object.keys(registrars).length} 家注册商 / ${priceCount} 条价格 (来自 ${source})`,
)
